list: $/ffte/clips/models/clip/columns.yaml
modelClass: Ffte\Clips\Models\Clip
title: Clips
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'ffte/clips/clips/update/:id'
